/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.BorderLayout;

/**
 *
 * @author Katy Diaz
 */
public class InterfazInicioGeneral extends javax.swing.JPanel {

    /**
     * Creates new form InterfazInicioGeneral
     */
    public InterfazInicioGeneral() {
        initComponents();
        transparenciaButton();
    }
    public void transparenciaButton(){
        GoAdmin.setOpaque(false);
        GoAdmin.setContentAreaFilled(false);
        GoAdmin.setBorderPainted(false);    
        
        GoCliente.setOpaque(false);
        GoCliente.setContentAreaFilled(false);
        GoCliente.setBorderPainted(false); 
        
        Salir.setOpaque(false);
        Salir.setContentAreaFilled(false);
        Salir.setBorderPainted(false); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoAdmin = new javax.swing.JButton();
        GoCliente = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoAdminActionPerformed(evt);
            }
        });
        add(GoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 190, 220));

        GoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoClienteActionPerformed(evt);
            }
        });
        add(GoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 220, 200));

        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 220, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenInicioFinal.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void GoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoAdminActionPerformed
      InterfazInicioAdmin InterfazInicioAdmin= new InterfazInicioAdmin();
      InterfazInicioAdmin.setSize(1000, 690);
        InterfazInicioAdmin.setLocation(0, 0);
        content.removeAll();
        content.add(InterfazInicioAdmin, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_GoAdminActionPerformed

    private void GoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoClienteActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoAdmin;
    private javax.swing.JButton GoCliente;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
