/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.BorderLayout;

/**
 *
 * @author Katy Diaz
 */
public class InterfazInicioAdmin extends javax.swing.JPanel {

    /**
     * Creates new form InterfazInicioAdmin
     */
    public InterfazInicioAdmin() {
        initComponents();
        transparenciaButton();
        
        DentroAdmin DentroAdmin= new DentroAdmin();
        DentroAdmin.setSize(1000,690);
        DentroAdmin.setLocation(0, 0);
        content.removeAll();
        content.add(DentroAdmin, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    public void transparenciaButton(){
    
        ButtonBack.setOpaque(false);
        ButtonBack.setContentAreaFilled(false);
        ButtonBack.setBorderPainted(false);
        
        InicioSesionAdmin.setOpaque(false);
        InicioSesionAdmin.setContentAreaFilled(false);
        InicioSesionAdmin.setBorderPainted(false);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicioSesionAdmin = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioSesionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioSesionAdminActionPerformed(evt);
            }
        });
        add(InicioSesionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 540, 230, 80));

        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });
        add(ButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 543, 90, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InicioAdmin.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void InicioSesionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioSesionAdminActionPerformed
         
// TODO add your handling code here:
    }//GEN-LAST:event_InicioSesionAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton InicioSesionAdmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
